### PR TITLE
Add option to allow coercion of array items

### LINKED ISSUE #6: array options should accept optional type parameter
see: https://github.com/bcoe/yargs/issues/372

something like:

``` js
parser([], {
  array: ['a', {key: 'b', type: 'string'}]
})
```

### PR DESCRIPTION
**Pull request by iilei**
Fixes #6

### CODE REVIEW

**Comment by bcoe** [comment]
@iilei this is awesome \o/ could I bother you to rebase?

Also, I apologize for the slow turnaround; it's hard to keep on top of open-source and all the exciting things happening at npm, Inc at the same time these days.

A good place to chat with me is [here](http://devtoolscommunity.herokuapp.com/), if my turn around is ever slow. A few folks who build node tooling are attempting to pull together a community around the needs of the developer tools community.

**Comment by iilei** [comment]
Rebase in progress

**Comment by bcoe** [comment]
@iilei 👍 let me know when this is ready to land.

**Comment by iilei** [comment]
@bcoe from my point of view it can be merged 👍

**Comment by bcoe** [comment]
@iilei likewise, try this out with `yargs@next` 👍 thank you for your contributions.

**Comment by iilei** [comment]
I am currently investigating on an [issue](https://github.com/iilei/kata-boilerplate/commit/8e8332ce6251c511315f99d2e2edfd9cf8913fcb#commitcomment-30801743) if there is a combination of multiple arrays, configured differently.

Please let me take some time to get this sorted out.

**Comment by iilei** [comment]
@bcoe I [figured](https://github.com/iilei/kata-boilerplate/commit/eeb286bc74de86118d048f61faf946c0bc8999a6) that the issue mentioned above is not due to my patch but also exists with version 12.0.2. 

Therefor, this patch is tested and true

**Comment by garyking** [comment]
Could someone explain how this option can be used with this:

```js
yargs.option('items', {
  alias: 'i',
  type: 'array',
  default: []
})
```

To coerce the array items to strings, even if something like `node script.js -i 123` is passed?

**Pull request merged**
