### PR TITLE
fix: `boolean-negation` configuration option wrong behaviour

### PR DESCRIPTION
**Pull request by ArthurKa**
Fix issue #376.

### CODE REVIEW

**Comment by jackcarnes** [comment]
approved

**Review by jackcarnes — APPROVED** [review]

**Review by jackcarnes — APPROVED** [review]
Appoved

**Comment by ArthurKa** [comment]
;)

**Comment by bcoe** [comment]
@ArthurKa sorry for the slow turnaround on this. Could I bother you to add a unit test for this behavior, otherwise it will regress again 😆

**Pull request closed without merging**
