### PR TITLE
allow non string values to be passed for values

### PR DESCRIPTION
**Pull request by lee-elenbaas**
allows for parsing of arrays like: ['--param', 15]

### CODE REVIEW

**Comment by nexdrew** [comment]
Before we review this, would you mind describing the use-case(s) this will help solve apart from doing something like the following?

```js
var parse = require('yargs-parser')
parse(['-f', 11, '--zoom', 55].join(' ')) // <-- array to single string
parse(['-f', 11, '--zoom', 55].map(String)) // <-- array of strings
```

**Comment by bcoe** [comment]
@lee-elenbaas I think I'd rather keep the explicit contract that `yargs-parser` expects an array of strings, does @nexdrew's suggestion of:

`parse(['-f', 11, '--zoom', 55].map(String))`

provide a reasonable workaround for you?

**Comment by lee-elenbaas** [comment]
It is the workaround i am currently using - at the very least - that contract should be documented

**Comment by nexdrew** [comment]
> at the very least - that contract should be documented

@lee-elenbaas Sounds reasonable to me. Thanks for bringing this up and for your understanding in this matter!

**Pull request closed without merging**
