### PR TITLE
Camel-Case-Expansion: alias by Property names, not Pathes

### PR DESCRIPTION
**Pull request by iilei**
This fixes issue #77
This *is* a breaking change

### CODE REVIEW

**Comment by bcoe** [comment]
@iilei thank you for this contribution ... while this is a breaking change, it feels like it's definitely addressing a bug (and I can't imagine many folks in yargs relying on the old behavior). My temptation is to call it a breaking change in yargs-parser, but to make it a patch in yargs ... then there's a paper trail for folks if it does break anyone, but we don't release a new yargs major.

**Comment by iilei** [comment]
@bcoe thank you for merging.

> My temptation is to call it a breaking change in yargs-parser, but to make it a patch in yargs

I would tend to do the same, for the same reasons. I can imagine it is more likely people have worked around it using aliases rather than relying on it. But that's just my uneducated guess

**Comment by bcoe** [comment]
@iilei this is now available in `npm i yargs@next` mind taking it for a spin and letting me know if things work alright?

**Comment by iilei** [comment]
@bcoe here is a code-kata repository / branch on which I verified it works:

https://github.com/iilei/kata-boilerplate/commit/0f244788b6eb246982123fbe9a8827323486ce13

**Pull request merged**
