### PR TITLE
Fix: ensure consistent parsing of dot-notation arguments

### LINKED ISSUE #101: Inconsistent parsing of arrays with dot-notation when argument order is switched
The way an array argument is parsed changes depending on whether I parse `--config.compression=store --config ./electron.config.json` vs. `--config ./electron.config.json --config.compression=store`

When I run:
```
var argv = require("yargs-parser")('--config.compression=store --config ./electron.config.json')
```

The value of `argv.compression` is
```json
[
  {
    "compression": "store"
  },
  "./electron.config.json"
]
```

But when I swap the arguments and run:
```
var argv = require("yargs-parser")('--config ./electron.config.json --config.compression=store')
```

The value of `argv.compression` is
```json
"\"./electron.config.json\""
```

I would expect them both to equal the result of the first command. Is there a reason for this, or is it a bug?

### PR DESCRIPTION
**Pull request by elsbree**
Fixes #101

### CODE REVIEW

**Comment by bcoe** [comment]
@elsbree this looks solid 👍 will work on getting it landed soon. thanks for the contribution.

**Comment by bcoe** [comment]
@elsbree sorry I dropped this on the ground for so long; could I bother you to rebase?

**Comment by elsbree** [comment]
I think I made a bit of a mess with that rebase- sorry about that.

**Comment by bcoe** [comment]
@elsbree I apologize for taking a long time to land things lately, have been pretty slammed with work.

appreciate the contribution 👍

**Pull request merged**
