### PR TITLE
tests: failing test for array config arg

### PR DESCRIPTION
**Pull request by JaKXz**
For #82.

### CODE REVIEW

**Comment by bcoe** [comment]
@JaKXz any interest in getting this over the finish line? I've been putting in bit more time against yargs, in prep for getting the next major release out the door (with better support for configuring veriadic options in commands).

**Comment by JaKXz** [comment]
@bcoe hey sorry for the delayed response, I can try taking a look but I can't promise a lot of dedicated time ATM.

**Comment by JaKXz** [comment]
FWIW I rebased and set the test to pending for now, so this can be merged and someone could take a crack at it :)

**Comment by bcoe** [comment]
@JaKXz 👍 let's keep this open a bit longer, no rush.

**Comment by bcoe** [comment]
@JaKXz just doing some cleanup; Is this still something you'd like to address eventually?

**Pull request closed without merging**
